### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by JNightRider** [neph1/JaimesAscent#1]
Hi @neph1 

You recently posted on the [forum](https://hub.jmonkeyengine.org/t/december-2024-monthly-wip-screenshot-thread/48047?u=swiftwolf) that this project is a template and I wanted to try it out, however it seems that the necessary models and textures are missing. Everything indicates that these resources are found in the [jme3-testdata](https://github.com/jMonkeyEngine/jmonkeyengine/tree/master/jme3-testdata) module. Do we have to include it in the dependency tree or add it manually?

```bash
GRAVE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetNotFoundException: Models/Jaime/Jaime.j3o
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:387)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:441)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:446)
	at jme3test.jaimesascent.GameState.setupCharacter(GameState.java:166)
	at jme3test.jaimesascent.GameState.initialize(GameState.java:83)
	at com.jme3.app.state.BaseAppState.initialize(BaseAppState.java:129)
	at com.jme3.app.state.AppStateManager.initializePending(AppStateManager.java:332)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:362)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:260)
	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:629)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:719)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by neph1** [comment]
Yes, my bad. I thought I had added it.
